name:                pregx
version:             0.1.0.0
github:              "githubuser/pregx"
author:              "Adam Frederik Ingwersen Linnemann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- MonadRandom

library:
  source-dirs: src

executables:
  pregx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XFlexibleContexts
    dependencies:
    - pregx